AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/doorkeeper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'
    - 'bin/*'

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/Output:
  Exclude:
    - 'config/unicorn.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'features/support/locale.rb'

Style/Documentation:
  Enabled: false

Style/UnneededPercentQ:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*rb'
    - 'spec/**/*_spec.rb'
    - 'lib/tasks/cucumber.rake'
    - 'config/routes.rb'


Metrics/MethodLength:
  Exclude:
    - 'app/models/ability.rb'

Style/RedundantSelf:
  Exclude:
#    - 'app/models/*'
