require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/doorkeeper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/Output:
  Exclude:
    - 'config/unicorn.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'features/support/locale.rb'

Style/Documentation:
  Enabled: false

Style/UnneededPercentQ:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*rb'
    - 'spec/**/*_spec.rb'
    - 'lib/tasks/cucumber.rake'
    - 'config/routes.rb'


Metrics/MethodLength:
  Exclude:
    - 'app/models/ability.rb'

Style/RedundantSelf:
  Exclude:
#    - 'app/models/*'
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*.rb'
RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*.rb'
    - 'spec/api/**/*.rb'
RSpec/NestedGroups:
  Max: 4
Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
