require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/doorkeeper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120

Lint/RaiseException:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'config/initializers/active_storage.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*rb'
    - 'spec/**/*_spec.rb'
    - 'lib/tasks/cucumber.rake'
    - 'config/routes.rb'
    - 'config/initializers/rails_admin.rb'
    - 'app/views/pages/feeds.builder'

Metrics/MethodLength:
  Exclude:
    - 'app/models/ability.rb'

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Rails:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*.rb'
    - 'spec/api/**/*.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*.rb'

RSpec/NestedGroups:
  Max: 4

Style/ClassAndModuleChildren:
  Exclude:
    - 'features/support/locale.rb'

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantPercentQ:
  Exclude:
    - 'spec/**/*_spec.rb'
