AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/Output:
  Exclude:
    - 'config/unicorn.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/UnneededPercentQ:
  Exclude:
    - 'spec/**/*_spec.rb'

Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

Layout/SpaceInsideBrackets:
  Exclude:
    - 'config/environments/production.rb'

Style/StringLiterals:
  Exclude:
    - 'bin/yarn'
    - 'config/environments/production.rb'
    - 'config/puma.rb'

Style/ConditionalAssignment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'config/deploy.rb'
    - 'config/environments/*rb'
    - 'spec/**/*_spec.rb'
    - 'lib/tasks/cucumber.rake'


Metrics/MethodLength:
  Exclude:
    - 'app/models/ability.rb'

Style/RedundantSelf:
  Exclude:
    - 'app/models/*'
