AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/Output:
  Exclude:
    - 'config/unicorn.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

Style/ConditionalAssignment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'config/deploy.rb'
    - 'spec/**/*_spec.rb'
Style/RedundantSelf:
  Exclude:
    - 'app/models/*'
