language: ruby
rvm:
  - 2.5.1
addons:
  apt:
    update: true
services:
  - postgresql
before_script:
  - export MUSEUM_DATABASE_TEST_NAME=travis_ci_test
  - export ADMIN_AUTH_NAME=name
  - export ADMIN_AUTH_PASSWORD=password
  - export RAILS_ENV=test
  - psql -c "create database travis_ci_test;" -U postgres
  - cd /usr/local/share
  - sudo wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - sudo tar xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - export PATH="$PATH:/usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/"
  - cd $TRAVIS_BUILD_DIR
  - yarn install
  - bin/webpack
script: 'bundle exec ruby script/ci/travis.rb'
