language: ruby
rvm:
  - 2.4.1
addons:
  apt:
    update: true
services:
  - postgresql
before_script:
  - export MUSEUM_DATABASE_TEST_NAME=travis_ci_test
  - export ADMIN_AUTH_NAME=name
  - export ADMIN_AUTH_PASSWORD=password
  - psql -c "create database travis_ci_test;" -U postgres
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - sudo cp --remove-destination phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/
  - sudo rm -rf phantomjs-2.1.1-linux-x86_64
script: 'bundle exec ruby script/ci/travis.rb'
