rvm:
  - 2.4.1
services:
  - postgresql
before_script:
  - export MUSEUM_DATABASE_TEST_NAME=travis_ci_test
  - export ADMIN_AUTH_NAME=name
  - export ADMIN_AUTH_PASSWORD=password
  - psql -c "create database travis_ci_test;" -U postgres
script: ' ruby script/ci/travis.rb'