language: ruby
rvm:
  - 2.5.1
addons:
  apt:
    update: true
services:
  - postgresql
before_script:
  - export MUSEUM_DATABASE_TEST_NAME=travis_ci_test
  - export ADMIN_AUTH_NAME=name
  - export ADMIN_AUTH_PASSWORD=password
  - psql -c "create database travis_ci_test;" -U postgres
  - sudo apt install xvfb  xauth qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
script: 'bundle exec ruby script/ci/travis.rb'
