language: ruby
rvm:
  - 2.6.3
env:
  - RAILS_ENV=test MUSEUM_DATABASE_TEST_NAME=travis_ci_test ADMIN_AUTH_NAME=name ADMIN_AUTH_PASSWORD=password NODE_ENV=test
addons:
  apt:
    update: true
services:
  - postgresql
install:
  - gem install bundler
  - bundle install
  - nvm install v12
  - nvm use v12
  - yarn
  - ./bin/rails webpacker:binstubs
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - bundle audit check --update
  - bundle exec rubocop .
  - bundle exec rspec
  - bundle exec cucumber
