version: '2'

volumes:
  db-data:
    external: false

services:
  prod_db:
    env_file: .env.prod
    image: postgres:9.5
    volumes:
      - db-data:/usr/local/psql/data_prod
  prod_app:
    env_file: .env.prod
    build:
      context: .
      dockerfile: $PWD/Dockerfile-production
    volumes:
      - .:/usr/src/app_prod
    ports:
      - '8080:8080'
    depends_on:
      - prod_db
