default: &default
  adapter: postgresql
  username: <%= ENV['MUSEUM_DATABASE_USERNAME'] %>
  password: <%= ENV['MUSEUM_DATABASE_PASSWORD'] %>
  database: <%= ENV['MUSEUM_DATABASE_DEV_NAME'] %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['MUSEUM_DATABASE_HOST'] %>

development:
  <<: *default

test: &test
  <<: *default
  database: <%= ENV['MUSEUM_DATABASE_TEST_NAME'] %>
  host: <%= ENV['MUSEUM_DATABASE_HOST'] %>

production:
  <<: *default
  database: <%= ENV['MUSEUM_DATABASE_PROD_NAME'] %>
  username: <%= ENV['MUSEUM_DATABASE_USERNAME'] %>
  password: <%= ENV['MUSEUM_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
