default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  database: museum_db
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: museum_test

production:
  <<: *default
  database: museum_production
  username: museum
  password: <%= ENV['MUSEUM_DATABASE_PASSWORD'] %>
