default: &default
  adapter: postgresql
  database: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :name) %>
  username: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :username) %>
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :password) %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :host) %>

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default

cucumber:
  <<: *test
