default: &default
  adapter: postgresql
  username: ubuntu
  password: password
  database: museum
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['MUSEUM_DATABASE_TEST_NAME'] %>

production:
  <<: *default
  database: museum
  username: ubuntu
  password: password
